### ISSUE TITLE
Operations in background

### ISSUE THREAD

**Issue by RandolfCarter** [owncloud/android-library#64]
I am working on an integration of owncloud upload capabilities into the gpslogger android app (https://github.com/mendhak/gpslogger).
Following the documentation of the android-library (https://doc.owncloud.org/server/8.0/developer_manual/android_library/index.html), what I struggled with is getting upload of a file to run from a background thread. As far as I can see, the current API doesn't directly support that, there's two issues: (1) for the Factory to create a OwnCloudClient, one needs a context; and (2) for the UploadRemoteFileOperation.execute, one needs a Handler (but that can't be created in a background thread if I understand correctly - it fails with "Can't create a handler inside thread that has not called Looper.prepare()").
Circumventing (1) is easy through the readily available constructor. For (2), to avoid having to create a Handler. I ended up calling the run() method directly; for that, the UploadRemoteFileOperation class had to be made public, but then it worked.

I'm quite new to Android development so probably I've just missed a simple thing, if so, I would be very thankful if you pointed me in the right direction!

**Comment by davivel** [comment]
@RandolfCarter , sorry for reponding so late. 

It's possible to create a ```Handler``` for other threads with other constructors, such as http://developer.android.com/reference/android/os/Handler.html#Handler(android.os.Looper) . But probably that's not what you need.

I guess that you don't need an asynchronous callback after the operation finishes, and in this case would be better that we relax the preconditions of the ```execute``` method and don't throw an exception if Handler is null. Another option is overloading the ```execute``` method as done in the already linked #77. 

It's very nice to see that other people is able to take advantage of the library out of the ownCloud app itslef. Thanks for your feedback!

Since your issue seems fixed with the solution by @mendhak, I'll close this issue, and ping you also when merge it, probably soon.

Thanks!
